# Generated by Django 4.2.11 on 2025-03-20 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("experiment", models.CharField(default="", max_length=60)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("type", models.CharField(default="", max_length=60)),
                ("value", models.FloatField(default=0.0)),
            ],
        ),
    ]
