# Generated by Django 5.0.2 on 2025-02-17 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("experiment", models.CharField(default="", max_length=60)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("type", models.CharField(default="", max_length=60)),
                ("value", models.FloatField(default=0.0)),
            ],
        ),
    ]
