# Generated by Django 4.2.11 on 2025-03-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("viewData", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Measurement",
        ),
    ]
